# m_config.py
AWS_ACCESS_KEY = "AKIATFQNJMD3R6BWEE5O"
AWS_SECRET_ACCESS_KEY = "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"
AWS_S3_BUCKET_REGION = "ap-northeast-2"
AWS_S3_BUCKET_NAME = "peachmarket-bucket"